### ISSUE TITLE
Inovelli Red Series Notification Settings - Feature Request

### ISSUE THREAD

**Issue by SebastienViel** [MFornander/Hubitat#12]
First, love the new feature that allows to control the Notification Setting for Inovelli switches directly in the app!

There are two settings in the Inovelli tool that are not in the new Notification settings.  I have been using both, so would love if there were also included:
1. Brightness Level
2. Duration

Thanks!

**Comment by MFornander** [comment]
1. Brightness can be accessed by using the large square to the right of the vertical color hue strip.  Selecting a darker version of the hue controls brightness. Not obvious so will add instructions on this.
2. Not going to allow duration since at that point, the app thinks the LED is on and will not show lower priority conditions.  The app has to be the authority of the LED states for priorities to work.

**Comment by MFornander** [comment]
Added more info on Brightness

**Comment by SebastienViel** [comment]
Understood for the timer...

For the brightness, Thanks for the clarification!  I should have spent a bit more time figuring it out.  In hindsight, it is pretty obvious, so the documentation is great!

I notice that the Inovelli tool allows for brightness 1 where the app only goes to 2.  I have a dimmer notification in my bedroom on a dimmer that I want at 1...  I can use the tool, but if the app went to 1, I would use the app.  Thanks!!!

Is the gray shades on top for when white will be available?  Right now, it does Red.  Intentional?
