### ISSUE TITLE
Upgrading to version 1.6 looses Inovelli custom value

### ISSUE THREAD

**Issue by SebastienViel** [MFornander/Hubitat#13]
Moving from 1.5.3 to 1.6.0, the Inovelli custom values are no longer in the app.

**Comment by MFornander** [comment]
As in the custom values do not show up in the UI, or something else?

**Comment by MFornander** [comment]
Oh I think I see what you mean.  I had to move around a bunch of variables in state and settings, so you previous custom values would not come through in v1.6.  I didn't see it since I was just resetting the state every time I was debugging it.  Srry, I'll be more careful in future versions so it doesn't happen again.

**Comment by SebastienViel** [comment]
No worries!  Thanks for the reply.
