### ISSUE TITLE
Trigger events

### ISSUE THREAD

**Issue by nitrocs** [MFornander/Hubitat#2]
I currently have a RM app that lights my LED notifications solid red normally when doors are opened.  When doors open while HSM is armed, the LEDs flash red -- any way to add this logic for trigger events?

**Comment by MFornander** [comment]
There are two requests here.  One is a HSM rule and the other is a blink request.

I've specifically stayed away from going down the path of recreating full RuleMachine logic since it's beyond my resources.  I would need to add AND/OR/NOT etc etc.  You could create a small virtual switch that is set by RM4 that is on when HSM is armed and the door is open, and then link to that switch in a condition in Switch Dashboard as a high priority condition that wins over just "door open".  I know it's not ideal but keeping the UI simple is and not going too complex is one of my missions with this app.

I did add Blink support for both HomeSeer and Inovelli in v1.2 just committed, so closing this issue as done :)
